class_name ParcaListesi
extends RefCounted
## OTOMATİK ÜRETİLDİ: tools/sahne_uret.gd — elle düzenleme.

const DUZ := "res://scenes/parcalar/01_duz.tscn"

const YOLLAR: Array[String] = [
	"res://scenes/parcalar/01_duz.tscn",
	"res://scenes/parcalar/02_tek_diken.tscn",
	"res://scenes/parcalar/03_kucuk_cukur.tscn",
	"res://scenes/parcalar/04_iki_diken.tscn",
	"res://scenes/parcalar/05_basamak.tscn",
	"res://scenes/parcalar/06_blok.tscn",
	"res://scenes/parcalar/07_genis_cukur.tscn",
	"res://scenes/parcalar/08_platform.tscn",
	"res://scenes/parcalar/09_merdiven.tscn",
	"res://scenes/parcalar/10_diken_blok.tscn",
	"res://scenes/parcalar/11_buyuk_cukur.tscn",
	"res://scenes/parcalar/12_cukur_diken.tscn",
	"res://scenes/parcalar/13_nefes_altin.tscn",
	"res://scenes/parcalar/14_nefes_asansor.tscn",
	"res://scenes/parcalar/15_nefes_kiris.tscn",
	"res://scenes/parcalar/16_alcak_gecit.tscn",
	"res://scenes/parcalar/17_piston.tscn",
	"res://scenes/parcalar/18_alcak_diken.tscn",
	"res://scenes/parcalar/19_iki_piston.tscn",
	"res://scenes/parcalar/20_hareketli_kopru.tscn",
	"res://scenes/parcalar/21_riskli_rota.tscn",
	"res://scenes/parcalar/22_basamak_diken.tscn",
	"res://scenes/parcalar/23_cift_cukur.tscn",
	"res://scenes/parcalar/24_piston_cukur.tscn",
	"res://scenes/parcalar/25_uzun_gecit.tscn",
	"res://scenes/parcalar/26_merdiven_blok.tscn",
	"res://scenes/parcalar/27_zincir_kiris.tscn",
	"res://scenes/parcalar/28_tavan_piston.tscn",
	"res://scenes/parcalar/29_nefes_merdiven.tscn",
	"res://scenes/parcalar/30_nefes_yildiz.tscn",
	"res://scenes/parcalar/31_blok_cukur.tscn",
	"res://scenes/parcalar/32_uclu_diken.tscn",
	"res://scenes/parcalar/33_asansor_cukur.tscn",
	"res://scenes/parcalar/34_tavan_cukur.tscn",
	"res://scenes/parcalar/35_cift_piston_cukur.tscn",
	"res://scenes/parcalar/36_nefes_kopru.tscn",
	"res://scenes/parcalar/37_curuk_iskele.tscn",
	"res://scenes/parcalar/38_iskele_zinciri.tscn",
	"res://scenes/parcalar/39_iskele_diken.tscn",
	"res://scenes/parcalar/40_uzun_iskele.tscn",
]

const ZORLUK := {
	"res://scenes/parcalar/01_duz.tscn": 1,
	"res://scenes/parcalar/02_tek_diken.tscn": 1,
	"res://scenes/parcalar/03_kucuk_cukur.tscn": 1,
	"res://scenes/parcalar/04_iki_diken.tscn": 1,
	"res://scenes/parcalar/05_basamak.tscn": 1,
	"res://scenes/parcalar/06_blok.tscn": 2,
	"res://scenes/parcalar/07_genis_cukur.tscn": 2,
	"res://scenes/parcalar/08_platform.tscn": 2,
	"res://scenes/parcalar/09_merdiven.tscn": 2,
	"res://scenes/parcalar/10_diken_blok.tscn": 3,
	"res://scenes/parcalar/11_buyuk_cukur.tscn": 3,
	"res://scenes/parcalar/12_cukur_diken.tscn": 3,
	"res://scenes/parcalar/13_nefes_altin.tscn": 0,
	"res://scenes/parcalar/14_nefes_asansor.tscn": 0,
	"res://scenes/parcalar/15_nefes_kiris.tscn": 0,
	"res://scenes/parcalar/16_alcak_gecit.tscn": 1,
	"res://scenes/parcalar/17_piston.tscn": 1,
	"res://scenes/parcalar/18_alcak_diken.tscn": 2,
	"res://scenes/parcalar/19_iki_piston.tscn": 2,
	"res://scenes/parcalar/20_hareketli_kopru.tscn": 2,
	"res://scenes/parcalar/21_riskli_rota.tscn": 2,
	"res://scenes/parcalar/22_basamak_diken.tscn": 2,
	"res://scenes/parcalar/23_cift_cukur.tscn": 3,
	"res://scenes/parcalar/24_piston_cukur.tscn": 3,
	"res://scenes/parcalar/25_uzun_gecit.tscn": 3,
	"res://scenes/parcalar/26_merdiven_blok.tscn": 3,
	"res://scenes/parcalar/27_zincir_kiris.tscn": 2,
	"res://scenes/parcalar/28_tavan_piston.tscn": 2,
	"res://scenes/parcalar/29_nefes_merdiven.tscn": 0,
	"res://scenes/parcalar/30_nefes_yildiz.tscn": 0,
	"res://scenes/parcalar/31_blok_cukur.tscn": 3,
	"res://scenes/parcalar/32_uclu_diken.tscn": 2,
	"res://scenes/parcalar/33_asansor_cukur.tscn": 3,
	"res://scenes/parcalar/34_tavan_cukur.tscn": 3,
	"res://scenes/parcalar/35_cift_piston_cukur.tscn": 3,
	"res://scenes/parcalar/36_nefes_kopru.tscn": 0,
	"res://scenes/parcalar/37_curuk_iskele.tscn": 1,
	"res://scenes/parcalar/38_iskele_zinciri.tscn": 2,
	"res://scenes/parcalar/39_iskele_diken.tscn": 2,
	"res://scenes/parcalar/40_uzun_iskele.tscn": 3,
}
